[package]
name = "input-display"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium = "0.30.2"
scan_fmt = "0.2.6"
x11rb = "0.9.0"